[package]
name = "dlsite-manager"
version = "0.4.0"
description = "manage your DLsite accounts and products at once"
authors = ["AcrylicShrimp"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.1", features = [] }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
parking_lot = { version = "0.12" }
reqwest = { version = "0.11", features = ["cookies", "json"] }
reqwest_cookie_store = { version = "0.4" }
rusqlite = { version = "0.28", features = ["bundled", "chrono"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.24" }
strum_macros = { version = "0.24" }
tauri = { version = "1.1", features = ["dialog", "shell-open"] }
thiserror = { version = "1" }
zip-extract = { git = "https://github.com/AcrylicShrimp/zip-extract", tag="v1.0.1", features = ["deflate"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
