name: dlsite_manager
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dev_dependencies:
  melos: ^7.1.1

workspace:
  - app
  - packages/dm_api

melos:
  scripts:
    codegen: melos exec --scope="dm_api" -- flutter pub run build_runner build --delete-conflicting-outputs
    dev: melos exec --scope="app" -- flutter run
    test: melos exec -- flutter test
