import type { DLsiteProductAge, DLsiteProductType } from "@app/types/product";

export const DisplayTypeString: Record<DLsiteProductType, string> = {
  Adult: "アダルト",
  Doujinsji: "同人誌",
  Software: "ソフトウェア",
  Game: "ゲーム",
  Action: "ゲーム",
  Adventure: "ゲーム",
  AudioMaterial: "音声作品",
  Comic: "コミック",
  DigitalNovel: "ノベル",
  Other: "その他",
  OtherGame: "ゲーム",
  Illust: "イラスト/CG",
  ImageMaterial: "画像作品",
  Manga: "マンガ",
  Anime: "アニメ/動画",
  Music: "音楽",
  Novel: "ノベル",
  Puzzle: "ゲーム",
  Quiz: "ゲーム",
  RolePlaying: "ゲーム",
  Gekiga: "コミック",
  Simulation: "ゲーム",
  Voice: "音声",
  Shooter: "ゲーム",
  Tabletop: "ゲーム",
  Utility: "ユーティリティ",
  Typing: "タイピング",
  SexualNovel: "ノベル",
  VoiceComic: "ボイスドラマ",
  Unknown: "不明",
};

export const BgCssType: Record<DLsiteProductType, string> = {
  Adult: "bg-[#bf2a13]",
  Doujinsji: "bg-[#98a11a]",
  Software: "bg-[#119147]",
  Game: "bg-[#148db5]",
  Action: "bg-[#148db5]",
  Adventure: "bg-[#148db5]",
  AudioMaterial: "bg-[#8a7b13]",
  Comic: "bg-[#30a149]",
  DigitalNovel: "bg-[#1e9463]",
  Other: "bg-[#525252]",
  OtherGame: "bg-[#148db5]",
  Illust: "bg-[#a81950]",
  ImageMaterial: "bg-[#8a7b13]",
  Manga: "bg-[#98a11a]",
  Anime: "bg-[#ab4a1a]",
  Music: "bg-[#7034bf]",
  Novel: "bg-[#1e9463]",
  Puzzle: "bg-[#148db5]",
  Quiz: "bg-[#148db5]",
  RolePlaying: "bg-[#148db5]",
  Gekiga: "bg-[#30a149]",
  Simulation: "bg-[#148db5]",
  Voice: "bg-[#7034bf]",
  Shooter: "bg-[#148db5]",
  Tabletop: "bg-[#148db5]",
  Utility: "bg-[#119147]",
  Typing: "bg-[#1e9463]",
  SexualNovel: "bg-[#1e9463]",
  VoiceComic: "bg-[#525252]",
  Unknown: "bg-[#525252]",
};

export const BgCssAge: Record<DLsiteProductAge, string> = {
  All: "bg-[#22910c]",
  R15: "bg-[#b38510]",
  R18: "bg-[#bf2a13]",
  Unknown: "bg-[#525252]",
};
