name: Build Windows Version
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Fix Workspace Config
        run: |
          echo "packages:" > pnpm-workspace.yaml
          echo "  - 'src-ui'" >> pnpm-workspace.yaml
          echo "  - 'src-tauri'" >> pnpm-workspace.yaml

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dlsite-manager-windows-build
          path: |
            **/target/release/bundle/msi/*.msi
            **/target/release/bundle/nsis/*.exe
          if-no-files-found: warn
          